version: '3'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
# docker-compose -f docker-compose.yml up --build -d database